CREATE TABLE IF NOT EXISTS posts(
    id SERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    image TEXT,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);